spring:
  #配置数据源信息
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置链接数据的各个信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatisplus?serverTimezone=GMT%2B8&characterEncoding=utf-8&&useSSL=true
    username: root
    password: 123123
#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #配置 src/main/resources/mapper/mybatis-plus.xml 自定义方法的位置 默认为当前位置
  #mapper-locations:
  #方式二：设置实体类对应表的前缀
  global-config:
    db-config:
      table-prefix: t_
      #设置统一的主键生成策略
      id-type: auto
  #配置类型别名对应的包
  type-aliases-package: com.gjc.mybatisplus.pojo
  #扫描通用枚举的包
  type-enums-package: com.gjc.mybatisplus.enums